services:
    php:
        environment:
            XDEBUG_MODE: develop,debug
            XDEBUG_CONFIG: "client_host=host.docker.internal client_port=9003"
        extra_hosts:
            - "host.docker.internal:host-gateway"  # Для Linux/macOS/Windows
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        volumes:
            - .:/var/www
        networks:
            - app-network
        restart: unless-stopped

    nginx:
        image: nginx:1.25-alpine
        ports:
            - "80:80"
        volumes:
            - .:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
        networks:
            - app-network
        restart: unless-stopped

networks:
    app-network:
        driver: bridge
